//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0507_PictureClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/_0507_PictureService")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Isbn {
            get {
                return this.IsbnField;
            }
            set {
                if ((this.IsbnField.Equals(value) != true)) {
                    this.IsbnField = value;
                    this.RaisePropertyChanged("Isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBook")]
    public interface IBook {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/C_Insert", ReplyAction="http://tempuri.org/IBook/C_InsertResponse")]
        bool C_Insert(int isbn, string title, string author, string publisher, int price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/C_Insert", ReplyAction="http://tempuri.org/IBook/C_InsertResponse")]
        System.Threading.Tasks.Task<bool> C_InsertAsync(int isbn, string title, string author, string publisher, int price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/C_Update", ReplyAction="http://tempuri.org/IBook/C_UpdateResponse")]
        bool C_Update(int isbn, string title, string author, string publisher, int price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/C_Update", ReplyAction="http://tempuri.org/IBook/C_UpdateResponse")]
        System.Threading.Tasks.Task<bool> C_UpdateAsync(int isbn, string title, string author, string publisher, int price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/C_Select_Isbn", ReplyAction="http://tempuri.org/IBook/C_Select_IsbnResponse")]
        string C_Select_Isbn(int isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/C_Select_Isbn", ReplyAction="http://tempuri.org/IBook/C_Select_IsbnResponse")]
        System.Threading.Tasks.Task<string> C_Select_IsbnAsync(int isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/C_Delete", ReplyAction="http://tempuri.org/IBook/C_DeleteResponse")]
        bool C_Delete(int isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/C_Delete", ReplyAction="http://tempuri.org/IBook/C_DeleteResponse")]
        System.Threading.Tasks.Task<bool> C_DeleteAsync(int isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/C_Select_All", ReplyAction="http://tempuri.org/IBook/C_Select_AllResponse")]
        _0507_PictureClient.ServiceReference1.Book[] C_Select_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/C_Select_All", ReplyAction="http://tempuri.org/IBook/C_Select_AllResponse")]
        System.Threading.Tasks.Task<_0507_PictureClient.ServiceReference1.Book[]> C_Select_AllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookChannel : _0507_PictureClient.ServiceReference1.IBook, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookClient : System.ServiceModel.ClientBase<_0507_PictureClient.ServiceReference1.IBook>, _0507_PictureClient.ServiceReference1.IBook {
        
        public BookClient() {
        }
        
        public BookClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool C_Insert(int isbn, string title, string author, string publisher, int price) {
            return base.Channel.C_Insert(isbn, title, author, publisher, price);
        }
        
        public System.Threading.Tasks.Task<bool> C_InsertAsync(int isbn, string title, string author, string publisher, int price) {
            return base.Channel.C_InsertAsync(isbn, title, author, publisher, price);
        }
        
        public bool C_Update(int isbn, string title, string author, string publisher, int price) {
            return base.Channel.C_Update(isbn, title, author, publisher, price);
        }
        
        public System.Threading.Tasks.Task<bool> C_UpdateAsync(int isbn, string title, string author, string publisher, int price) {
            return base.Channel.C_UpdateAsync(isbn, title, author, publisher, price);
        }
        
        public string C_Select_Isbn(int isbn) {
            return base.Channel.C_Select_Isbn(isbn);
        }
        
        public System.Threading.Tasks.Task<string> C_Select_IsbnAsync(int isbn) {
            return base.Channel.C_Select_IsbnAsync(isbn);
        }
        
        public bool C_Delete(int isbn) {
            return base.Channel.C_Delete(isbn);
        }
        
        public System.Threading.Tasks.Task<bool> C_DeleteAsync(int isbn) {
            return base.Channel.C_DeleteAsync(isbn);
        }
        
        public _0507_PictureClient.ServiceReference1.Book[] C_Select_All() {
            return base.Channel.C_Select_All();
        }
        
        public System.Threading.Tasks.Task<_0507_PictureClient.ServiceReference1.Book[]> C_Select_AllAsync() {
            return base.Channel.C_Select_AllAsync();
        }
    }
}
