#include <windows.h>

LRESULT CALLBACK WndProc(HWND,UINT,WPARAM,LPARAM);
HINSTANCE g_hInst;
HWND hWndMain;
LPCTSTR lpszClass=TEXT("SysMetrics");

int APIENTRY WinMain(HINSTANCE hInstance,HINSTANCE hPrevInstance
	  ,LPSTR lpszCmdParam,int nCmdShow)
{
	HWND hWnd;
	MSG Message;
	WNDCLASS WndClass;
	g_hInst=hInstance;

	WndClass.cbClsExtra=0;
	WndClass.cbWndExtra=0;
	WndClass.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);
	WndClass.hCursor=LoadCursor(NULL,IDC_ARROW);
	WndClass.hIcon=LoadIcon(NULL,IDI_APPLICATION);
	WndClass.hInstance=hInstance;
	WndClass.lpfnWndProc=WndProc;
	WndClass.lpszClassName=lpszClass;
	WndClass.lpszMenuName=NULL;
	WndClass.style=CS_HREDRAW | CS_VREDRAW;
	RegisterClass(&WndClass);

	hWnd=CreateWindow(lpszClass,lpszClass,WS_OVERLAPPEDWINDOW,
		CW_USEDEFAULT,CW_USEDEFAULT,CW_USEDEFAULT,CW_USEDEFAULT,
		NULL,(HMENU)NULL,hInstance,NULL);
	ShowWindow(hWnd,nCmdShow);

	while (GetMessage(&Message,NULL,0,0)) {
		TranslateMessage(&Message);
		DispatchMessage(&Message);
	}
	return (int)Message.wParam;
}

struct tag_Metrics {
	int nIndex;
	TCHAR *Name;
}arSM[]={
	{SM_ARRANGE,"SM_ARRANGE"},
	{SM_CLEANBOOT,"SM_CLEANBOOT"},
//	{SM_CMONITORS,"SM_CMONITORS"},
	{SM_CMOUSEBUTTONS,"SM_CMOUSEBUTTONS"},
	{SM_CXBORDER,"SM_CXBORDER"},
	{SM_CYBORDER,"SM_CYBORDER"},
	{SM_CXCURSOR,"SM_CXCURSOR"},
	{SM_CYCURSOR,"SM_CYCURSOR"},
	{SM_CXDLGFRAME,"SM_CXDLGFRAME"},
	{SM_CYDLGFRAME,"SM_CYDLGFRAME"},
	{SM_CXDOUBLECLK,"SM_CXDOUBLECLK"},
	{SM_CYDOUBLECLK,"SM_CYDOUBLECLK"},
	{SM_CXDRAG,"SM_CXDRAG"},
	{SM_CYDRAG,"SM_CYDRAG"},
	{SM_CXEDGE,"SM_CXEDGE"},
	{SM_CYEDGE,"SM_CYEDGE"},
	{SM_CXFIXEDFRAME,"SM_CXFIXEDFRAME"},
	{SM_CYFIXEDFRAME,"SM_CYFIXEDFRAME"},
	{SM_CXFRAME,"SM_CXFRAME"},
	{SM_CYFRAME,"SM_CYFRAME"},
	{SM_CXFULLSCREEN,"SM_CXFULLSCREEN"},
	{SM_CYFULLSCREEN,"SM_CYFULLSCREEN"},
	{SM_CXHSCROLL,"SM_CXHSCROLL"},
	{SM_CYHSCROLL,"SM_CYHSCROLL"},
	{SM_CXHTHUMB,"SM_CXHTHUMB"},
	{SM_CXICON,"SM_CXICON"},
	{SM_CYICON,"SM_CYICON"},
	{SM_CXICONSPACING,"SM_CXICONSPACING"},
	{SM_CYICONSPACING,"SM_CYICONSPACING"},
	{SM_CXMAXIMIZED,"SM_CXMAXIMIZED"},
	{SM_CYMAXIMIZED,"SM_CYMAXIMIZED"},
	{SM_CXMAXTRACK,"SM_CXMAXTRACK"},
	{SM_CYMAXTRACK,"SM_CYMAXTRACK"},
	{SM_CXMENUCHECK,"SM_CXMENUCHECK"},
	{SM_CYMENUCHECK,"SM_CYMENUCHECK"},
	{SM_CXMENUSIZE,"SM_CXMENUSIZE"},
	{SM_CYMENUSIZE,"SM_CYMENUSIZE"},
	{SM_CXMIN,"SM_CXMIN"},
	{SM_CYMIN,"SM_CYMIN"},
	{SM_CXMINIMIZED,"SM_CXMINIMIZED"},
	{SM_CYMINIMIZED,"SM_CYMINIMIZED"},
	{SM_CXMINSPACING,"SM_CXMINSPACING"},
	{SM_CYMINSPACING,"SM_CYMINSPACING"},
	{SM_CXMINTRACK,"SM_CXMINTRACK"},
	{SM_CYMINTRACK,"SM_CYMINTRACK"},
	{SM_CXSCREEN,"SM_CXSCREEN"},
	{SM_CYSCREEN,"SM_CYSCREEN"},
	{SM_CXSIZE,"SM_CXSIZE"},
	{SM_CYSIZE,"SM_CYSIZE"},
	{SM_CXSIZEFRAME,"SM_CXSIZEFRAME"},
	{SM_CYSIZEFRAME,"SM_CYSIZEFRAME"},
	{SM_CXSMICON,"SM_CXSMICON"},
	{SM_CYSMICON,"SM_CYSMICON"},
	{SM_CXSMSIZE,"SM_CXSMSIZE"},
	{SM_CYSMSIZE,"SM_CYSMSIZE"},
//	{SM_CXVIRTUALSCREEN,"SM_CXVIRTUALSCREEN"},
//	{SM_CYVIRTUALSCREEN,"SM_CYVIRTUALSCREEN"},
	{SM_CXVSCROLL,"SM_CXVSCROLL"},
	{SM_CYVSCROLL,"SM_CYVSCROLL"},
	{SM_CYCAPTION,"SM_CYCAPTION"},
	{SM_CYKANJIWINDOW,"SM_CYKANJIWINDOW"},
	{SM_CYMENU,"SM_CYMENU"},
	{SM_CYSMCAPTION,"SM_CYSMCAPTION"},
	{SM_CYVTHUMB,"SM_CYVTHUMB"},
	{SM_DBCSENABLED,"SM_DBCSENABLED"},
	{SM_DEBUG,"SM_DEBUG"},
//	{SM_IMMENABLED,"SM_IMMENABLED"},
	{SM_MENUDROPALIGNMENT,"SM_MENUDROPALIGNMENT"},
	{SM_MIDEASTENABLED,"SM_MIDEASTENABLED"},
	{SM_MOUSEPRESENT,"SM_MOUSEPRESENT"},
//	{SM_MOUSEWHEELPRESENT,"SM_MOUSEWHEELPRESENT"},
	{SM_NETWORK,"SM_NETWORK"},
	{SM_PENWINDOWS,"SM_PENWINDOWS"},
//	{SM_REMOTESESSION,"SM_REMOTESESSION"},
	{SM_SECURE,"SM_SECURE"},
//	{SM_SAMEDISPLAYFORMAT,"SM_SAMEDISPLAYFORMAT"},
	{SM_SHOWSOUNDS,"SM_SHOWSOUNDS"},
	{SM_SLOWMACHINE,"SM_SLOWMACHINE"},
	{SM_SWAPBUTTON,"SM_SWAPBUTTON"},
//	{SM_XVIRTUALSCREEN,"SM_XVIRTUALSCREEN"},
//	{SM_YVIRTUALSCREEN,"SM_YVIRTUALSCREEN"}
};

LRESULT CALLBACK WndProc(HWND hWnd,UINT iMessage,WPARAM wParam,LPARAM lParam)
{
	HDC hdc;
	PAINTSTRUCT ps;
	int i;
	TCHAR str[255];
	switch (iMessage) {
	case WM_CREATE:
		return 0;
	case WM_PAINT:
		hdc=BeginPaint(hWnd, &ps);
		for (i=0;i<sizeof(arSM)/sizeof(arSM[0]);i++) {
			wsprintf(str,"%s=%d",arSM[i].Name,GetSystemMetrics(arSM[i].nIndex));
			TextOut(hdc,(i/30)*250,(i % 30)*16,str,lstrlen(str));
		}
		EndPaint(hWnd, &ps);
		return 0;
	case WM_DESTROY:
		PostQuitMessage(0);
		return 0;
	}
	return(DefWindowProc(hWnd,iMessage,wParam,lParam));
}

