//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo_Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zoo", Namespace="http://schemas.datacontract.org/2004/07/Zoo_Service")]
    [System.SerializableAttribute()]
    public partial class Zoo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IZoo")]
    public interface IZoo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZoo/Insert", ReplyAction="http://tempuri.org/IZoo/InsertResponse")]
        bool Insert(int id, string name, string country, int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZoo/Insert", ReplyAction="http://tempuri.org/IZoo/InsertResponse")]
        System.Threading.Tasks.Task<bool> InsertAsync(int id, string name, string country, int age);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IZoo/Delete")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IZoo/Delete")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZoo/Select", ReplyAction="http://tempuri.org/IZoo/SelectResponse")]
        Zoo_Client.ServiceReference1.Zoo Select(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZoo/Select", ReplyAction="http://tempuri.org/IZoo/SelectResponse")]
        System.Threading.Tasks.Task<Zoo_Client.ServiceReference1.Zoo> SelectAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZoo/Update", ReplyAction="http://tempuri.org/IZoo/UpdateResponse")]
        bool Update(int id, string name, string country, int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZoo/Update", ReplyAction="http://tempuri.org/IZoo/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(int id, string name, string country, int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZoo/Select_All", ReplyAction="http://tempuri.org/IZoo/Select_AllResponse")]
        Zoo_Client.ServiceReference1.Zoo[] Select_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZoo/Select_All", ReplyAction="http://tempuri.org/IZoo/Select_AllResponse")]
        System.Threading.Tasks.Task<Zoo_Client.ServiceReference1.Zoo[]> Select_AllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZooChannel : Zoo_Client.ServiceReference1.IZoo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZooClient : System.ServiceModel.ClientBase<Zoo_Client.ServiceReference1.IZoo>, Zoo_Client.ServiceReference1.IZoo {
        
        public ZooClient() {
        }
        
        public ZooClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZooClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZooClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZooClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Insert(int id, string name, string country, int age) {
            return base.Channel.Insert(id, name, country, age);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAsync(int id, string name, string country, int age) {
            return base.Channel.InsertAsync(id, name, country, age);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public Zoo_Client.ServiceReference1.Zoo Select(int id) {
            return base.Channel.Select(id);
        }
        
        public System.Threading.Tasks.Task<Zoo_Client.ServiceReference1.Zoo> SelectAsync(int id) {
            return base.Channel.SelectAsync(id);
        }
        
        public bool Update(int id, string name, string country, int age) {
            return base.Channel.Update(id, name, country, age);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(int id, string name, string country, int age) {
            return base.Channel.UpdateAsync(id, name, country, age);
        }
        
        public Zoo_Client.ServiceReference1.Zoo[] Select_All() {
            return base.Channel.Select_All();
        }
        
        public System.Threading.Tasks.Task<Zoo_Client.ServiceReference1.Zoo[]> Select_AllAsync() {
            return base.Channel.Select_AllAsync();
        }
    }
}
