// 스타일
#define GSS_HORZ 1
#define GSS_VERT 2

// 메시지
#define GSM_SETRANGE WM_USER+1
#define GSM_GETRANGEHI WM_USER+2
#define GSM_GETRANGELOW WM_USER+3
#define GSM_SETPOS WM_USER+4
#define GSM_GETPOS WM_USER+5
#define GSM_SETTSIZE WM_USER+6
#define GSM_GETTSIZE WM_USER+7
#define GSM_SETTGAP WM_USER+8
#define GSM_GETTGAP WM_USER+9
#define GSM_SETBACKCOLOR WM_USER+10
#define GSM_SETTHUMBCOLOR WM_USER+11

