//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _05059_시험_Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/_0509_%EC%8B%9C%ED%97%98_Service")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAccount")]
    public interface IAccount {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/InsertAccount", ReplyAction="http://tempuri.org/IAccount/InsertAccountResponse")]
        bool InsertAccount(int id, string name, int balance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/InsertAccount", ReplyAction="http://tempuri.org/IAccount/InsertAccountResponse")]
        System.Threading.Tasks.Task<bool> InsertAccountAsync(int id, string name, int balance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/InputMoney", ReplyAction="http://tempuri.org/IAccount/InputMoneyResponse")]
        bool InputMoney(int id, int money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/InputMoney", ReplyAction="http://tempuri.org/IAccount/InputMoneyResponse")]
        System.Threading.Tasks.Task<bool> InputMoneyAsync(int id, int money);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAccount/DeleteAccount")]
        void DeleteAccount(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAccount/DeleteAccount")]
        System.Threading.Tasks.Task DeleteAccountAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/SelectAccount", ReplyAction="http://tempuri.org/IAccount/SelectAccountResponse")]
        _05059_시험_Client.ServiceReference1.Account SelectAccount(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/SelectAccount", ReplyAction="http://tempuri.org/IAccount/SelectAccountResponse")]
        System.Threading.Tasks.Task<_05059_시험_Client.ServiceReference1.Account> SelectAccountAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/SelectAllAccount", ReplyAction="http://tempuri.org/IAccount/SelectAllAccountResponse")]
        _05059_시험_Client.ServiceReference1.Account[] SelectAllAccount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/SelectAllAccount", ReplyAction="http://tempuri.org/IAccount/SelectAllAccountResponse")]
        System.Threading.Tasks.Task<_05059_시험_Client.ServiceReference1.Account[]> SelectAllAccountAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountChannel : _05059_시험_Client.ServiceReference1.IAccount, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountClient : System.ServiceModel.ClientBase<_05059_시험_Client.ServiceReference1.IAccount>, _05059_시험_Client.ServiceReference1.IAccount {
        
        public AccountClient() {
        }
        
        public AccountClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertAccount(int id, string name, int balance) {
            return base.Channel.InsertAccount(id, name, balance);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAccountAsync(int id, string name, int balance) {
            return base.Channel.InsertAccountAsync(id, name, balance);
        }
        
        public bool InputMoney(int id, int money) {
            return base.Channel.InputMoney(id, money);
        }
        
        public System.Threading.Tasks.Task<bool> InputMoneyAsync(int id, int money) {
            return base.Channel.InputMoneyAsync(id, money);
        }
        
        public void DeleteAccount(int id) {
            base.Channel.DeleteAccount(id);
        }
        
        public System.Threading.Tasks.Task DeleteAccountAsync(int id) {
            return base.Channel.DeleteAccountAsync(id);
        }
        
        public _05059_시험_Client.ServiceReference1.Account SelectAccount(int id) {
            return base.Channel.SelectAccount(id);
        }
        
        public System.Threading.Tasks.Task<_05059_시험_Client.ServiceReference1.Account> SelectAccountAsync(int id) {
            return base.Channel.SelectAccountAsync(id);
        }
        
        public _05059_시험_Client.ServiceReference1.Account[] SelectAllAccount() {
            return base.Channel.SelectAllAccount();
        }
        
        public System.Threading.Tasks.Task<_05059_시험_Client.ServiceReference1.Account[]> SelectAllAccountAsync() {
            return base.Channel.SelectAllAccountAsync();
        }
    }
}
