//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0508_Book_Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/_0508_Book_Service")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBook", CallbackContract=typeof(_0508_Book_Client.ServiceReference1.IBookCallback))]
    public interface IBook {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/Insert", ReplyAction="http://tempuri.org/IBook/InsertResponse")]
        bool Insert(int id, string title, string author, int price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/Insert", ReplyAction="http://tempuri.org/IBook/InsertResponse")]
        System.Threading.Tasks.Task<bool> InsertAsync(int id, string title, string author, int price);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBook/Delete")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBook/Delete")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/Select", ReplyAction="http://tempuri.org/IBook/SelectResponse")]
        _0508_Book_Client.ServiceReference1.Book[] Select(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/Select", ReplyAction="http://tempuri.org/IBook/SelectResponse")]
        System.Threading.Tasks.Task<_0508_Book_Client.ServiceReference1.Book[]> SelectAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/Update", ReplyAction="http://tempuri.org/IBook/UpdateResponse")]
        bool Update(int id, string title, string author, int price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/Update", ReplyAction="http://tempuri.org/IBook/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(int id, string title, string author, int price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/Select_All", ReplyAction="http://tempuri.org/IBook/Select_AllResponse")]
        _0508_Book_Client.ServiceReference1.Book[] Select_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/Select_All", ReplyAction="http://tempuri.org/IBook/Select_AllResponse")]
        System.Threading.Tasks.Task<_0508_Book_Client.ServiceReference1.Book[]> Select_AllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBook/Notify_Print_All")]
        void Notify_Print_All(string[] return_All);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookChannel : _0508_Book_Client.ServiceReference1.IBook, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookClient : System.ServiceModel.DuplexClientBase<_0508_Book_Client.ServiceReference1.IBook>, _0508_Book_Client.ServiceReference1.IBook {
        
        public BookClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public BookClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public BookClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public BookClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public BookClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool Insert(int id, string title, string author, int price) {
            return base.Channel.Insert(id, title, author, price);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAsync(int id, string title, string author, int price) {
            return base.Channel.InsertAsync(id, title, author, price);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public _0508_Book_Client.ServiceReference1.Book[] Select(int id) {
            return base.Channel.Select(id);
        }
        
        public System.Threading.Tasks.Task<_0508_Book_Client.ServiceReference1.Book[]> SelectAsync(int id) {
            return base.Channel.SelectAsync(id);
        }
        
        public bool Update(int id, string title, string author, int price) {
            return base.Channel.Update(id, title, author, price);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(int id, string title, string author, int price) {
            return base.Channel.UpdateAsync(id, title, author, price);
        }
        
        public _0508_Book_Client.ServiceReference1.Book[] Select_All() {
            return base.Channel.Select_All();
        }
        
        public System.Threading.Tasks.Task<_0508_Book_Client.ServiceReference1.Book[]> Select_AllAsync() {
            return base.Channel.Select_AllAsync();
        }
    }
}
